"""Local file storage. Each video gets its own directory:

    storage/videos/<id>/
        meta.json       VideoRecord
        original.<ext>  the uploaded file
"""

import json
import re
from pathlib import Path

from .config import get_settings
from .models import VideoRecord

_ID_RE = re.compile(r"^[0-9a-f]{32}$")


def videos_root() -> Path:
    root = get_settings().storage_path / "videos"
    root.mkdir(parents=True, exist_ok=True)
    return root


def video_dir(video_id: str) -> Path:
    # IDs are generated by us (uuid4 hex); reject anything else so a crafted
    # ID can never escape the storage directory.
    if not _ID_RE.match(video_id):
        raise KeyError(video_id)
    return videos_root() / video_id


def save_record(record: VideoRecord) -> None:
    path = video_dir(record.id) / "meta.json"
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(record.model_dump_json(indent=2))
    tmp.replace(path)


def load_record(video_id: str) -> VideoRecord:
    try:
        path = video_dir(video_id) / "meta.json"
        return VideoRecord.model_validate_json(path.read_text())
    except (KeyError, FileNotFoundError) as exc:
        raise KeyError(video_id) from exc


def list_records() -> list[VideoRecord]:
    records = []
    for meta in videos_root().glob("*/meta.json"):
        try:
            records.append(VideoRecord.model_validate_json(meta.read_text()))
        except ValueError:
            continue
    return sorted(records, key=lambda r: r.uploaded_at, reverse=True)


def video_file(record: VideoRecord) -> Path:
    return video_dir(record.id) / record.stored_filename


def write_json(video_id: str, name: str, data: object) -> None:
    path = video_dir(video_id) / name
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(data))
    tmp.replace(path)


def read_json(video_id: str, name: str) -> object | None:
    path = video_dir(video_id) / name
    if not path.exists():
        return None
    return json.loads(path.read_text())
