import type { FeedbackResult } from "../api/types";

interface Props {
  result: FeedbackResult | null;
  busy: boolean;
  onRegenerate: () => void;
  onHighlight: (keys: string[]) => void;
}

const PRIORITY_LABEL = { high: "High priority", medium: "Medium", low: "Low" };

export default function FeedbackPanel({ result, busy, onRegenerate, onHighlight }: Props) {
  const regen = (
    <button onClick={onRegenerate} disabled={busy}>
      {busy ? "Working…" : "Regenerate feedback"}
    </button>
  );

  if (!result || result.status !== "ok") {
    return (
      <section className="card feedback">
        <div className="feedback-header">
          <h2>Coaching feedback</h2>
          {regen}
        </div>
        <p className={result?.status === "error" ? "error" : "muted"}>
          {result ? result.error : "Feedback hasn't been generated yet."}
        </p>
      </section>
    );
  }

  const fb = result.feedback;
  const hoverProps = (keys: string[]) => ({
    onMouseEnter: () => onHighlight(keys),
    onMouseLeave: () => onHighlight([]),
  });

  return (
    <section className="card feedback">
      <div className="feedback-header">
        <h2>Coaching feedback</h2>
        {regen}
      </div>
      <p className="feedback-summary">{fb.summary}</p>

      <div className="focus">
        <span className="focus-label">Next session focus</span>
        {fb.next_session_focus}
      </div>

      {fb.issues.length > 0 && (
        <>
          <h3>What to work on</h3>
          {fb.issues.map((issue) => (
            <article key={issue.title} className="issue" {...hoverProps(issue.metric_keys)}>
              <div className="issue-title">
                <span className={`priority priority-${issue.priority}`}>{PRIORITY_LABEL[issue.priority]}</span>
                <strong>{issue.title}</strong>
              </div>
              <p>{issue.explanation}</p>
              <details>
                <summary>Drill: {issue.drill.name}</summary>
                <p>{issue.drill.how_to}</p>
                <p className="muted">{issue.drill.why}</p>
              </details>
            </article>
          ))}
        </>
      )}

      {fb.strengths.length > 0 && (
        <>
          <h3>What's working</h3>
          <ul className="strengths">
            {fb.strengths.map((s) => (
              <li key={s.title} {...hoverProps(s.metric_keys)}>
                <strong>{s.title}.</strong> {s.detail}
              </li>
            ))}
          </ul>
        </>
      )}

      {fb.caveats.length > 0 && (
        <p className="muted small">Note: {fb.caveats.join(" ")}</p>
      )}
      <p className="muted small">Generated by {result.model}. Hover an item to highlight its metrics.</p>
    </section>
  );
}
